prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix acl: <http://www.w3.org/2001/02/acls#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?photo ?created ?jpg

where {
    # XXX TODO: Eventually use friends/family/private too, but this requires
    # authenticated URLs.
    ?photo a <x-urn:flickr:photo> ;
        acl:accessor "public" ;
        dc:created ?created .

    ?jpg rdfs:seeAlso ?photo ;
        dcterms:relation "Original" .

    filter not exists {
        ?photo dc:subject <http://www.flickr.com/photos/35468142996@N01/tags/lauren> .

        # XXX FIXME: This will also pick up other Laurens.  Do a date
        # restriction like, but with syntax that actually works:
        #filter (2006 <= year(?created) && year(?created) <= 2007) .
    }
}

order by ?created ?photo

# vim: set syn=sparql:
